### ISSUE TITLE
No space for screw heads on one side

### ISSUE THREAD

**Issue by jps2000** [adafruit/Adafruit-nRF52-Bluefruit-Feather-PCB#2]
There is almost no space for screws on the MDBT42 side. in particular the LED is endangered.
Pls improve  in the next layout if possible. Find attached my suggestions.
[adafruit feather nrf52 revG_JPS.zip](https://github.com/adafruit/Adafruit-nRF52-Bluefruit-Feather-PCB/files/2612101/adafruit.feather.nrf52.revG_JPS.zip)

**Comment by ladyada** [comment]
thanks for the note! these are already in production, and we're unlikely to do any revisions soon - but when we do we'll move the LED as well :)

**Comment by jps2000** [comment]
Thanks. 
Of course I understand that. 
Lets follow the basic wisdom "never change a running system"

**Comment by ladyada** [comment]
indeed :)
